---
AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  RoleARN:
    Type: String
  MyVPC:
    Type: AWS::EC2::VPC::Id
  DBSubnet1:
    Type: AWS::EC2::Subnet::Id
  DBSubnet2:
    Type: AWS::EC2::Subnet::Id
  DBSubnet3:
    Type: AWS::EC2::Subnet::Id
Resources:
  DataLoadFunction:
    Type: AWS::Lambda::Function
    Properties:
      Handler: lambda_function.lambda_handler
      Code:
        S3Bucket: curriki-eks-ali-west
        S3Key: CurrikiDemo/DataLoadFunction/DataLoadFunction.zip
      Role:
        Ref: RoleARN
      Runtime: python3.7
      Timeout: 900
      VpcConfig:
        SecurityGroupIds:
        - Ref: LambdaSecurityGroup
        SubnetIds:
        - Ref: DBSubnet1
        - Ref: DBSubnet2
        - Ref: DBSubnet3
  LambdaSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Group for Lambda Instance
      VpcId:
        Ref: MyVPC
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 5432
        ToPort: 5432
        CidrIp: 10.0.0.0/16
Outputs:
  FunctionARN:
    Description: FunctionARN
    Value:
      Fn::GetAtt:
      - DataLoadFunction
      - Arn
    Export:
      Name: FunctionARN
