AWSTemplateFormatVersion: '2010-09-09'
Description: 'EKS Cluster and Managed Nodes'
Metadata:

  Authors:
    Description: Ali Mehdi (ali@curriki.org)
  License:
    Description: 'Copyright 2021 Curriki.org, Inc. and its affiliates. All Rights Reserved.'

  AWS::CloudFormation::Interface:
    ParameterGroups:
    - Label:
        default: General AWS
      Parameters:
        - SshAccessCidr
    - Label:
        default: Network
      Parameters:
        - NumberOfAZs
        - AvailabilityZones
        - VpcCidr
        - VpcTenancy
        - PublicSubnet0Cidr
        - PublicSubnet1Cidr
        - PublicSubnet2Cidr
        - PublicSubnet3Cidr
        - PublicSubnet4Cidr
        - PublicSubnet5Cidr
        - PrivateSubnet0Cidr
        - PrivateSubnet1Cidr
        - PrivateSubnet2Cidr
        - PrivateSubnet3Cidr
        - PrivateSubnet4Cidr
        - PrivateSubnet5Cidr
    - Label:
        default: Bastion Tier
      Parameters:
        - BastionInstanceType
    - Label:
        default: Web Tier
      Parameters:
        - PublicAlbAcmCertificate
        - PHPVersion
        - PHPIniOverride
    ParameterLabels:
      BastionInstanceType:
        default: Bastion Instance Type
      PHPIniOverride:
        default: AWS php.ini Overrides
      PublicAlbAcmCertificate:
        default: ALB Certificate ARN
      SshAccessCidr:
        default: SSH Access From
      WebInstanceType:
        default: Web Tier Instance Type
      AvailabilityZones:
        default: Availability Zones
      NumberOfAZs:
        default: Number of Availability Zones
      VpcCidr:
        default: VpcCidr
      VpcTenancy:
        default: VpcTenancy
      PHPVersion:
        default: PHP Version
      PublicSubnet0Cidr:
        default: Public Subnet 0
      PublicSubnet1Cidr:
        default: Public Subnet 1
      PublicSubnet2Cidr:
        default: Public Subnet 2
      PublicSubnet3Cidr:
        default: Public Subnet 3
      PublicSubnet4Cidr:
        default: Public Subnet 4
      PublicSubnet5Cidr:
        default: Public Subnet 5
      PrivateSubnet0Cidr:
        default: Private Subnet 0
      PrivateSubnet1Cidr:
        default: Private Subnet 1
      PrivateSubnet2Cidr:
        default: Private Subnet 2
      PrivateSubnet3Cidr:
        default: Private Subnet 3
      PrivateSubnet4Cidr:
        default: Private Subnet 4
      PrivateSubnet5Cidr:
        default: Private Subnet 5

Parameters:
  SshAccessCidr:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$
    Description: The CIDR IP range that is permitted to SSH to bastion instance. Note - a value of 0.0.0.0/0 will allow access from ANY IP address.
    Type: String
    Default: 0.0.0.0/0
  AvailabilityZones:
    Description: 'List of Availability Zones to use for the subnets in the VPC. Note:
      The logical order is preserved.'
    Type: List<AWS::EC2::AvailabilityZone::Name>
  NumberOfAZs:
    AllowedValues:
    - 2
    - 3
    - 4
    - 5
    - 6
    Default: 3
    Description: Number of Availability Zones to use in the VPC. This must match your
      selections in the list of Availability Zones parameter.
    Type: Number
  VpcCidr:
    AllowedPattern: "^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\\/(1[6-9]|2[0-8]))$"
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: 10.0.0.0/16
    Description: CIDR block for the VPC
    Type: String
  VpcTenancy:
    AllowedValues:
    - default
    - dedicated
    Default: default
    Description: The allowed tenancy of instances launched into the VPC
    Type: String
  PublicSubnet0Cidr:
    AllowedPattern: "^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\\/(1[6-9]|2[0-8]))$"
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: 10.0.200.0/24
    Description: CIDR block for Public subnet 0 located in Availability Zone 0
    Type: String
  PublicSubnet1Cidr:
    AllowedPattern: "^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\\/(1[6-9]|2[0-8]))$"
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: 10.0.201.0/24
    Description: CIDR block for Public subnet 1 located in Availability Zone 1
    Type: String
  PublicSubnet2Cidr:
    AllowedPattern: "^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\\/(1[6-9]|2[0-8]))$"
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: 10.0.202.0/24
    Description: CIDR block for Public subnet 2 located in Availability Zone 2
    Type: String
  PublicSubnet3Cidr:
    AllowedPattern: "^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\\/(1[6-9]|2[0-8]))$"
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: 10.0.203.0/24
    Description: CIDR block for Public subnet 3 located in Availability Zone 3
    Type: String
  PublicSubnet4Cidr:
    AllowedPattern: "^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\\/(1[6-9]|2[0-8]))$"
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: 10.0.204.0/24
    Description: CIDR block for Public subnet 4 located in Availability Zone 4
    Type: String
  PublicSubnet5Cidr:
    AllowedPattern: "^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\\/(1[6-9]|2[0-8]))$"
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: 10.0.205.0/24
    Description: CIDR block for Public subnet 5 located in Availability Zone 5
    Type: String
  PrivateSubnet0Cidr:
    AllowedPattern: "^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\\/(1[6-9]|2[0-8]))$"
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: 10.0.0.0/22
    Description: CIDR block for Web subnet 0 located in Availability Zone 0
    Type: String
  PrivateSubnet1Cidr:
    AllowedPattern: "^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\\/(1[6-9]|2[0-8]))$"
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: 10.0.4.0/22
    Description: CIDR block for Web subnet 1 located in Availability Zone 1
    Type: String
  PrivateSubnet2Cidr:
    AllowedPattern: "^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\\/(1[6-9]|2[0-8]))$"
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: 10.0.8.0/22
    Description: CIDR block for Web subnet 2 located in Availability Zone 2
    Type: String
  PrivateSubnet3Cidr:
    AllowedPattern: "^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\\/(1[6-9]|2[0-8]))$"
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: 10.0.12.0/22
    Description: CIDR block for Web subnet 3 located in Availability Zone 3
    Type: String
  PrivateSubnet4Cidr:
    AllowedPattern: "^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\\/(1[6-9]|2[0-8]))$"
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: 10.0.16.0/22
    Description: CIDR block for Web subnet 4 located in Availability Zone 4
    Type: String
  PrivateSubnet5Cidr:
    AllowedPattern: "^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\\/(1[6-9]|2[0-8]))$"
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: 10.0.20.0/22
    Description: CIDR block for Web subnet 5 located in Availability Zone 5
    Type: String
  ClusterName: 
    Type: String
    Description: Name of your managed EKS Cluster
  AvailabilityZones:
    Description: 'List of Availability Zones to use for the subnets in the VPC. Note:
      The logical order is preserved.'
    Type: List<AWS::EC2::AvailabilityZone::Name>
  NumberOfAZs:
    AllowedValues:
    - 2
    - 3
    - 4
    - 5
    - 6
    Default: 3
    Description: Number of Availability Zones to use in the VPC. This must match your
      selections in the list of Availability Zones parameter.
    Type: Number
  LaravelFrontEndUrl:
    Type: String
    Description: Frontend App Url
    Default: https://k8s.currikistudio.org
  ReactAppPexelAPI:
    Type: String
    Description: Pexel API key
  ReactAppGoogleCaptcha:
    Type: String
    Description: React App Google Captcha
  ReactAppGoogleApiClientId:
    Type: String
    Description: React App Google Captcha
  ReactAppHubspot:
    Type: String
    Description: React App Hubspot
  ReactAppH5PKey:
    Type: String
    Description: React App H5P Key
  VpcCidrBlock:
    Type: String
    Description: CIDR Block for VPC
    Default: 10.0.0.0/16
  EksVersion:
    Type: String
    Description: EKS Version
    Default: "1.18"
    AllowedValues:
    - "1.17"
    - "1.18"
  EbsDiskSize:
    Type: Number
    Description: Size of EBS Volume to be attached with worker nodes
    Default: 30
  InstanceType:
    Type: String
    Description: Instance type for worker nodes
    ConstraintDescription: Must be a valid EC2 Instance Type
    Default: t2.xlarge
    AllowedValues:
      - t2.large
      - t2.xlarge
      - t2.2xlarge
      - m1.large
      - m1.xlarge
      - m2.xlarge
      - m2.2xlarge
      - m2.4xlarge
      - m3.medium
      - m3.large
      - m3.xlarge
      - m3.2xlarge
      - m4.large
      - m4.xlarge
      - m4.2xlarge
      - m4.4xlarge
      - m4.10xlarge
      - c1.medium
      - c1.xlarge
      - c3.large
      - c3.xlarge
      - c3.2xlarge
      - c3.4xlarge
      - c3.8xlarge
      - c4.large
      - c4.xlarge
      - c4.2xlarge
      - c4.4xlarge
      - c4.8xlarge
      - g2.2xlarge
      - g2.8xlarge
      - r3.large
      - r3.xlarge
      - r3.2xlarge
      - r3.4xlarge
      - r3.8xlarge
      - i2.xlarge
      - i2.2xlarge
      - i2.4xlarge
      - i2.8xlarge
      - d2.xlarge
      - d2.2xlarge
      - d2.4xlarge
      - d2.8xlarge
      - hi1.4xlarge
      - hs1.8xlarge
      - cr1.8xlarge
      - cc2.8xlarge
      - cg1.4xlarge
  SSHKeyPair:
    Description: Ec2 Keypair Name
    Type: AWS::EC2::KeyPair::KeyName
  MinWorkerNodes:
    Type: Number
    Description: Minimum no. of Worker nodes in EKS Cluster
    Default: 3
  MaxWorkerNodes:
    Type: Number
    Description: Maximum no. of Worker nodes in EKS Cluster
    Default: 5
  DesiredWorkerNodes:
    Type: Number
    Description: Desired no. of Worker nodes in EKS Cluster
    Default: 3
  EC2InstanceProfile: #CurrikiStackRole	
    Type: String
    Description: Instance Profile Name
  EC2InstanceRoleArn: # arn:aws:iam::946488682732:role/CloudFormationRegistryResourceLogRole	
    Type: String
    Description: EC2 Instance Profile ARN
  DatabaseInstanceType:
    Type: String
    Default: db.t3.xlarge
    Description: The Amazon RDS database instance class.
    ConstraintDescription: Must be a valid RDS instance class.
    Default: db.r4.large
    AllowedValues:
      - db.t2.small
      - db.r3.xlarge
      - db.r3.2xlarge
      - db.r3.4xlarge
      - db.r3.8xlarge
      - db.r4.large
      - db.r4.xlarge
      - db.r4.2xlarge
      - db.r4.4xlarge
      - db.r4.8xlarge
      - db.r4.16xlarge
      - db.t3.xlarge
  ElasticSearchUser:
    Type: String
  ElasticSearchPassword:
    Type: String
    NoEcho: true
  RedisPassword:
    Type: String
    NoEcho: true
    Description: Password for Redis cache
  Route53RecordDNS:
    Type: String
    Default: k8s.currikistudio.org
  HostedZoneID:
    Type: String
  AdminUrl:
    Type: String
    Default: admin-studio.currikistudio.org
  DomainName:
    Type: String
    Default: currikistudio.org
Resources:
  EksCluster:
    Type: AWS::CloudFormation::Stack
    Properties: 
      Parameters:
        ClusterName: !Ref ClusterName
        EksVersion: !Ref EksVersion
        VpcCidrBlock: !Ref VpcCidrBlock
        PublicSubnet1Cidr: !Ref PublicSubnet1Cidr
        PublicSubnet2Cidr: !Ref PublicSubnet2Cidr
        PublicSubnet3Cidr: !Ref PublicSubnet3Cidr
        PublicSubnet4Cidr: !Ref PublicSubnet4Cidr
        PrivateSubnet1Cidr: !Ref PrivateSubnet1Cidr
        PrivateSubnet2Cidr: !Ref PrivateSubnet2Cidr
        PrivateSubnet3Cidr: !Ref PrivateSubnet3Cidr
        PrivateSubnet4Cidr: !Ref PrivateSubnet4Cidr
        HostedZoneID: !Ref HostedZoneID
        DomainName: !Ref DomainName
        AvailabilityZones: 
          !Join
            - ','
            - !Ref AvailabilityZones
        NumberOfAZs: !Ref NumberOfAZs
      TemplateURL: https://studio-eks.s3.amazonaws.com/src/v2/templates/components/curriki-eks-01-cluster.yml
  EksNodeGroup:  
    DependsOn: EksCluster  
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        ClusterName: !Ref ClusterName
        EbsDiskSize: !Ref EbsDiskSize
        InstanceType: !Ref InstanceType
        SSHKeyPair: !Ref SSHKeyPair
        MinWorkerNodes: !Ref MinWorkerNodes
        MaxWorkerNodes: !Ref MaxWorkerNodes
        DesiredWorkerNodes: !Ref DesiredWorkerNodes
        PublicSubnets: !GetAtt EksCluster.Outputs.SubnetsPublic
      TemplateURL: https://studio-eks.s3.amazonaws.com/src/v2/templates/components/curriki-eks-02-nodegroup.yml
  DbStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://studio-eks.s3.amazonaws.com/src/v2/templates/components/curriki-eks-03-database-deploy.yml
      TimeoutInMinutes: 60
      Parameters:
        MyVPC: !GetAtt EksCluster.Outputs.VPC
        VpcCidrBlock: !Ref VpcCidrBlock
        PrivateSubnets: !GetAtt EksCluster.Outputs.SubnetsPrivate
        DatabaseInstanceType: !Ref DatabaseInstanceType
  EksDeployment:
    DependsOn: 
      - EksNodeGroup
      - DbStack
    Type: AWS::CloudFormation::Stack
    Properties: 
      Parameters:
        PublicSubnets: !GetAtt EksCluster.Outputs.SubnetsPublic
        SSHKeyPair: !Ref SSHKeyPair
        VpcId: !GetAtt EksCluster.Outputs.VPC
        ClusterName: !Ref ClusterName
        EC2InstanceProfile: !Ref EC2InstanceProfile
        EC2InstanceRoleArn: !Ref EC2InstanceRoleArn
        AvailabilityZones: 
          !Join
            - ','
            - !Ref AvailabilityZones
        NumberOfAZs: !Ref NumberOfAZs
        AcmCertArn: !GetAtt EksCluster.Outputs.AcmCertArn
        VpcCidrBlock: !Ref VpcCidrBlock
        Ec2SecurityGroupId: !GetAtt EksCluster.Outputs.Ec2SecurityGroupId
        LaravelFrontEndUrl: !Ref LaravelFrontEndUrl
        ReactAppPexelAPI: !Ref ReactAppPexelAPI
        ReactAppGoogleCaptcha: !Ref ReactAppGoogleCaptcha
        ReactAppGoogleApiClientId: !Ref ReactAppGoogleApiClientId
        ReactAppHubspot: !Ref ReactAppHubspot
        ReactAppH5PKey: !Ref ReactAppH5PKey
        RdsInstanceSecret: !GetAtt DbStack.Outputs.MyRDSInstanceSecret
        ElasticSearchUser: !Ref ElasticSearchUser
        ElasticSearchPassword: !Ref ElasticSearchPassword
        RedisPassword: !Ref RedisPassword
        Route53RecordDNS: !Ref Route53RecordDNS
        HostedZoneID: !Ref HostedZoneID
        AdminUrl: !Ref AdminUrl
        DomainName: !Ref DomainName
      TemplateURL: https://studio-eks.s3.amazonaws.com/src/v2/templates/components/curriki-eks-04-deployment.yml
